### ISSUE TITLE
Some observations

### ISSUE THREAD

**Issue by ghost** [dubhater/vapoursynth-xaa#1]
The errors below are encountered when trying equivalent settings for santiag and Mrdaa
https://github.com/dubhater/vapoursynth-xaa/blob/a04c5f8b9a3b722b89a4a4aa9713f2d387639a2a/xaa.py#L408
https://github.com/dubhater/vapoursynth-xaa/blob/a04c5f8b9a3b722b89a4a4aa9713f2d387639a2a/xaa.py#L410
https://github.com/dubhater/vapoursynth-xaa/blob/a04c5f8b9a3b722b89a4a4aa9713f2d387639a2a/xaa.py#L416
"planes" is not defined in the function definitions resulting unexpected argument error.
https://github.com/dubhater/vapoursynth-xaa/blob/a04c5f8b9a3b722b89a4a4aa9713f2d387639a2a/xaa.py#L527
TypeError: 'float' object is not iterable
https://github.com/dubhater/vapoursynth-xaa/blob/a04c5f8b9a3b722b89a4a4aa9713f2d387639a2a/xaa.py#L729
Maybe you mean mode[0]?
https://github.com/dubhater/vapoursynth-xaa/blob/a04c5f8b9a3b722b89a4a4aa9713f2d387639a2a/xaa.py#L767
mode="null" raise ValueError here
https://github.com/dubhater/vapoursynth-xaa/blob/a04c5f8b9a3b722b89a4a4aa9713f2d387639a2a/xaa.py#L946
false is not defined (should be False)

**Comment by dubhater** [comment]
Thanks for testing. I fixed them all.
