### ISSUE TITLE
Doesn't work with GRAY input

### ISSUE THREAD

**Issue by Doarom** [dubhater/vapoursynth-xaa#2]
I'm either doing something terribly wrong or the script doesn't handle GRAY input.

```File "C:\Users\Do\AppData\Roaming\Python\Python37\site-packages\xaa.py", line 1453, in xaa```
```eover = core.std.Expr(clips=eover, expr=["", "x 2 /"])```
```File "src\cython\vapoursynth.pyx", line 1833, in vapoursynth.Function.__call__```
```vapoursynth.Error: Expr: More expressions given than there are planes```

**Comment by dubhater** [comment]
I guess it's a bug.

**Comment by dubhater** [comment]
Please try again.

**Comment by Doarom** [comment]
Seems to work. Thank you for the quick fix.
