### ISSUE TITLE
Is this plugin only made for interlaced content?

### ISSUE THREAD

**Issue by damian101** [dubhater/vapoursynth-xaa#8]
From the description of "AA Mode" it appears so...
I only tried it on progressive content, and got the best results with AA Mode di instead of the default sr.

**Comment by shssoichiro** [comment]
This plugin should work just fine with progressive content. However, it does take some tweaking to get good results. I find that `mode="maa"` works well for animated content, but is too strong for live-action content. You might have decent luck with `mode="daa"`. Although it also depends on what you're trying to fix. If what you're dealing with is actually _residual combing_ from poor deinterlacing, you'll have better luck using QTGMC to fix that.
