### ISSUE TITLE
core.register_format() has been deprecated

### ISSUE THREAD

**Issue by JeremyMahieu** [dubhater/vapoursynth-xaa#9]
The function [has been deprecated](https://www.vapoursynth.com/doc/pythonreference.html?highlight=register_format#Core.register_format) in favor of query_video_format().

This makes xaa no longer work.

**Comment by banjaminicc** [comment]
> The function [has been deprecated](https://www.vapoursynth.com/doc/pythonreference.html?highlight=register_format#Core.register_format) in favor of query_video_format().
> 
> This makes xaa no longer work.

Did you figure out a workaround by any chance?
Or any alternative filters
